name: Deploy SBA

on:
  push:
    branches:
      - sba

jobs:
  deploy-sba:
    runs-on: ubuntu-latest
    name: Deploy SBA
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build dependencies
        continue-on-error: true
        run: |
          yarn install
          yarn build

      - name: Build SBA
        working-directory: ./packages/sba-eligibility
        run: |
          yarn install
          yarn build
          yarn build:gh
          yarn deploy
